---
name: lemon-squeezy
version: 1.0.0.0

license: OtherLicense
license-file: LICENSE

dependencies:
  - aeson
  - aeson-casing
  - base
  - bytestring
  - email-validate
  - generic-lens
  - genvalidity
  - genvalidity-containers
  - genvalidity-text
  - genvalidity-time
  - http-client
  - http-client-tls
  - http-media
  - optparse-applicative
  - optparse-generic
  - QuickCheck
  - relude
  - scientific
  - servant
  - servant-client
  - sydtest
  - text
  - time
  - url

library:
  source-dirs: ./src/

ghc-options:
  - -fwrite-ide-info
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wpartial-fields
  - -Widentities
  - -Wredundant-constraints
  - -Wcpp-undef
  - -Wunused-packages

tests:
  lemon-squeezy-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N
    dependencies:
      - genvalidity-sydtest
      - genvalidity-sydtest-aeson
      - lemon-squeezy
      - sydtest
      - sydtest-discover
      - sydtest-wai
